### ISSUE TITLE
ForceMatrixKernel test: an illegal memory access was encountered

### ISSUE THREAD

**Issue by tu-maurice** [ComputationalRadiationPhysics/nbody-alpaka#1]
Running the test with Cuda on Taurus:
[error.txt](https://github.com/ComputationalRadiationPhysics/nbody-alpaka/files/67558/error.txt)

Edit: AccCpuSerial as well es AccCpuOmp2Blocks and Threads run as expected.
It's probably the different hardware.
Maybe the compiler doesn't compile the operators for die GPU?

Edit2: Englisch.

**Comment by psychocoderHPC** [comment]
If the test used the optimized workdiv calculatiin from alpaka a invalid combination can be the reason. May be the calculated workdiv used too much shared memory.
Please enable debug lvl with ccmake and check rhe used extern shared memory at runtime.

**Comment by tu-maurice** [comment]
It does indeed use the workdiv calculation. Thanks, I'll check that.

**Comment by psychocoderHPC** [comment]
You can check for memory errors on device with `cuda-memcheck` and on the host with `valgrind`.
valgrind creates some false positives inside the alpaka library. Compile the device code with `-G` for device code and with `-g` for the host code to get the line numbers inside both program's.

**Comment by tu-maurice** [comment]
@psychocoderHPC 
Might this be a possible hint or cause or should I ignore it?

```
/home/s7745593/nbody-alpaka/alpaka/include/alpaka/vec/Vec.hpp(466): warning: calling a __host__ function("std::min<unsigned long> ") from a __host__ __device__ function("") is not allowed
```

**Comment by psychocoderHPC** [comment]
I think this is not a problem but we should fix it in alpaka.

**Comment by tu-maurice** [comment]
okay I thought it might be a clue to wrong use of the alpaka library.
The test with -G, valgrind and cuda-memcheck is currently in the queue of taurus. Will report later what it said.

**Comment by tu-maurice** [comment]
I reviewed the output of the job I ran yesterday and it says there is an illegal opcode.
[output-debug.txt](https://github.com/ComputationalRadiationPhysics/nbody-alpaka/files/69668/output-debug.txt)

**Comment by tu-maurice** [comment]
cuda-memcheck says

```
========= Invalid __global__ read of size 8
=========     at 0x000000b8 in _ZN6alpaka4exec4cuda6detail10cudaKernelISt17integral_constantImLm2EEmN5nbody10simulation7kernels17ForceMatrixKernelEJPNS7_5types6VectorILm2EfEEPfSD_mffEEEvNS_3VecIT_T0_EET1_DpT2_
=========     by thread (0,1,0) in block (0,0,0)
=========     Address 0x00000000 is out of bounds
```

for thread 0,1,0 and 1,0,0. Thread 0,0,0 and 1,1,0 (I think) do a different task (in this case nothing)

I might not sufficiently educated how memory is handled in C++ but our Vector class has an array created without new or malloc, I was pretty sure that the data is saved in the Vector memory itself but maybe the data is saved somewhere else and a pointer is saved in the Vector memory?

I'm gonna try to read a vector on the gpu with a test kernel.

**Comment by psychocoderHPC** [comment]
Could you please add a link to your vector class.

**Comment by tu-maurice** [comment]
Here you go: [vector.hpp Line 43](https://github.com/ComputationalRadiationPhysics/nbody-alpaka/blob/master/src/simulation/types/vector.hpp#L43)

**Comment by psychocoderHPC** [comment]
I reviewed your vector implementation on my smartphone and all looks fine.
Please keep in mind that alpaka vectors stored as (z,y,x) = idx(0,1,2) maybe you access your array with the wrong index order?

**Comment by tu-maurice** [comment]
I use a 2 dimensional index and request `alpaka::idx::getIdx<alpaka::Grid,alpaka::Threads>( acc )[ 0u ]` and `alpaka::idx::getIdx<alpaka::Grid,alpaka::Threads>( acc )[ 1u ]`.
The extent for both dimensions is the same and both indices are interchangable. Also I compute 1 element per thread.
( See [forceMatrixKernel.hpp:77](https://github.com/ComputationalRadiationPhysics/nbody-alpaka/blob/master/src/simulation/kernels/forceMatrixKernel.hpp#L77) )

I allocate the square matrix with the same extent that is used to execute the kernel.
[forcematrix_test.cpp:56](https://github.com/ComputationalRadiationPhysics/nbody-alpaka/blob/master/tests/forceMatrixKernel/forcematrix_test.cpp#L56) - definition of extent
[forcematrix_test.cpp:67](https://github.com/ComputationalRadiationPhysics/nbody-alpaka/blob/master/tests/forceMatrixKernel/forcematrix_test.cpp#L67) - extent in the workdiv
[forcematrix_test.cpp:120](https://github.com/ComputationalRadiationPhysics/nbody-alpaka/blob/master/tests/forceMatrixKernel/forcematrix_test.cpp#L120) - allocation of the matrix on the accelerator.

For the arrays I use a 1-dimensional extent but with the same size I used for one dimension in the extent for the matrix.
[forcematrix_test.cpp:51](https://github.com/ComputationalRadiationPhysics/nbody-alpaka/blob/master/tests/forceMatrixKernel/forcematrix_test.cpp#L51)

**Comment by psychocoderHPC** [comment]
Your force matrix on the device is 2d and each line is aligned. This means that you need byte pointer magic to access this memory. I think that this is not the reason for the error but not used correct. For more information please check cudaMallocPitched from the cuda api.

**Comment by psychocoderHPC** [comment]
I checked your vector class again and see that `ALPAKA_FN_ACC` is missing before each method of vector. Each method those is used on an accelerator must defined as `ALPAKA_FN_ACC`

**Comment by tu-maurice** [comment]
constructors too?

**Comment by psychocoderHPC** [comment]
yes constructor too

**Comment by tu-maurice** [comment]
Okay. I'm gonna have to reimplement one of the constructors as it depends an a host function but that should be fine for now as it's not used in the kernel at the moment.

The test still says illegal memory access with the difference that it now wants to read 4 instead of 8 bytes.

```
========= Invalid __global__ read of size 4
=========     at 0x00000148 in _ZN6alpaka4exec4cuda6detail10cudaKernelISt17integral_constantImLm2EEmN5nbody10simulation7kernels17ForceMatrixKernelEJPNS7_5types6VectorILm2EfEEPfSD_mmffEEEvNS_3VecIT_T0_EET1_DpT2_
=========     by thread (0,1,0) in block (0,0,0)
=========     Address 0x00000000 is out of bounds
(...)
========= Invalid __global__ read of size 4
=========     at 0x00000148 in _ZN6alpaka4exec4cuda6detail10cudaKernelISt17integral_constantImLm2EEmN5nbody10simulation7kernels17ForceMatrixKernelEJPNS7_5types6VectorILm2EfEEPfSD_mmffEEEvNS_3
VecIT_T0_EET1_DpT2_
=========     by thread (1,0,0) in block (0,0,0)
=========     Address 0x00000000 is out of bounds
```

again for (1,0,0) and (0,1,0).
~~(**Edit**: I noticed a difference in the "method names" which is a trailing VecIT_T0_EET1_DpT2_.)~~
**Edit 2**: Nope no difference

Size of Vector<2,float> is 8 bytes, so it's either one of the floats inside a vector or one float in a float array I also have as a parameter.
Also I assume as it is one-dimensional it doesn't need byte pointer pitch magic.

**Comment by tu-maurice** [comment]
Sorry, I forgot to divide the Pitch bytes by the size of Vector<2,float>.
Running it again.

**Comment by tu-maurice** [comment]
Apparently that didn't change anything.

Still the same error:

```
========= Invalid __global__ read of size 4
=========     at 0x00000148 in _ZN6alpaka4exec4cuda6detail10cudaKernelISt17integral_constantImLm2EEmN5nbody10simulation7kernels17ForceMatrixKernelEJPNS7_5types6VectorILm2EfEEPfSD_mmffEEEvNS_3VecIT_T0_EET1_DpT2_
=========     by thread (0,1,0) in block (0,0,0)
=========     Address 0x00000000 is out of bounds
========= Invalid __global__ read of size 4
=========     at 0x00000148 in _ZN6alpaka4exec4cuda6detail10cudaKernelISt17integral_constantImLm2EEmN5nbody10simulation7kernels17ForceMatrixKernelEJPNS7_5types6VectorILm2EfEEPfSD_mmffEEEvNS_3VecIT_T0_EET1_DpT2_
=========     by thread (1,0,0) in block (0,0,0)
=========     Address 0x00000000 is out of bounds
```

[output-readofsize4.txt](https://github.com/ComputationalRadiationPhysics/nbody-alpaka/files/70122/output-readofsize4.txt)

**Comment by psychocoderHPC** [comment]
Please add -G to your nvcc flags to get the line number inside the error message.

ccmake . #in the build folder
than press t and edit the cuda_nvcc_flags
than c and g
make
rerun your example

**Comment by tu-maurice** [comment]
I was pretty sure this line would do that: [CMakeLists.txt:32](https://github.com/ComputationalRadiationPhysics/nbody-alpaka/blob/force-matrix-test-cuda/tests/forceMatrixKernel/CMakeLists.txt#L32)
But sure I can do it manually.

**Comment by psychocoderHPC** [comment]
Please move it one line up to define it before the compile.

Am 22. Dezember 2015 21:07:53 MEZ, schrieb Valentin notifications@github.com:

> I was pretty sure this line would do that:
> [CMakeLists.txt:32](https://github.com/ComputationalRadiationPhysics/nbody-alpaka/blob/force-matrix-test-cuda/tests/forceMatrixKernel/CMakeLists.txt#L32)
> But sure I can do it manually.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ComputationalRadiationPhysics/nbody-alpaka/issues/1#issuecomment-166717692

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by tu-maurice** [comment]
Well that just throws an error because cmake doesn't know the target yet.
I'll try the ccmake variant.

**Comment by tu-maurice** [comment]
[forceMatrixKernel.hpp:123](https://github.com/ComputationalRadiationPhysics/nbody-alpaka/blob/force-matrix-test-cuda/src/simulation/kernels/forceMatrixKernel.hpp#L123) seems to create the error.
Although [forceMatrixKernel.hpp:92](https://github.com/ComputationalRadiationPhysics/nbody-alpaka/blob/force-matrix-test-cuda/src/simulation/kernels/forceMatrixKernel.hpp#L92) uses the same index pattern and doesn't cause an error.

I do have to ask again. Is this use of `getPitchBytes` correct? [forcematrix_test.cpp:147](https://github.com/ComputationalRadiationPhysics/nbody-alpaka/blob/force-matrix-test-cuda/tests/forceMatrixKernel/forcematrix_test.cpp#L147)

**Comment by psychocoderHPC** [comment]
The usage of pitch looks correct. Could you please add a printf inside the kernel and print out the calculated idx for the array access.

**Comment by psychocoderHPC** [comment]
Please check `sizeof(Vector)` that it is a power of 2 else the division of `pitch/sizeof(vector)` is not valid.

**Comment by psychocoderHPC** [comment]
the asserts in Vector are wrong.
https://github.com/ComputationalRadiationPhysics/nbody-alpaka/blob/force-matrix-test-cuda/src/simulation/types/vector.hpp#L300
Sould be `<` not `<=`

**Comment by tu-maurice** [comment]
1. printf added. Does that also work for the cuda Acc? because host function.
2. Size of Vector<2,float> (which is used in the test) is 2*sizeof(float) = 8. But I'll keep that in mind for 3 dimensional simulations.
3. removed =. Don't know why I wrote that.

I'll see if I can put that on the taurus from here.
**Edit2:** Sorry testing on the taurus will have to wait until 26th.

**Comment by psychocoderHPC** [comment]
Yes printf is allowed on nvidia gpus.

No problem we can solve the issu next year.

Merry Xmas!

**Comment by tu-maurice** [comment]
Okay. Merry Christmas to you too.

**Comment by bussmann** [comment]
Great teamwork here. Merry Christmas to you both!

**Comment by tu-maurice** [comment]
@bussmann Merry Christmas to you too.

**Comment by tu-maurice** [comment]
Today I had the chance to run the kernel and print out the calculated indexes, which are 0,1,64 and 65. I'm currently running it again to see if that matches the return value of getPitchBytes.
**Edit**: getPitchBytes returns 512. which results in 64 when divided by the size of Vector<2,float> which is 8 Bytes.

P.S.: Keep enjoying 2nd christmas day. I just wanted to add this as a note here.

**Comment by tu-maurice** [comment]
I added some more debug output and put it back into the taurus queue. I'll look at it later.

**Comment by psychocoderHPC** [comment]
I will check getPitchedBytes as I know cuda should return 128byte because that is the alignment of global memory

**Comment by tu-maurice** [comment]
Okay. i split the writing of the result and the multiplication of forceFactor and positionRelative into 2 separate lines and the error occured in the multiplication.
I looked into the vector.hpp again and apparently i forgot to add ALPAKA_FN_ACC to the multiplication operator outside of the class at the bottom of the file.
I am pretty sure that created the last error. I am currently running the test again just to be sure.

@psychocoderHPC are you sure? 128 sounds like 512 divided by sizeof(float) to me.

**Comment by tu-maurice** [comment]
It works...

**Comment by psychocoderHPC** [comment]
Congratulation! 
What is the finale solution?

**Comment by tu-maurice** [comment]
A missing ALPAKA_FN_ACC in the vector.hpp.
0ab0d0c

**Comment by bussmann** [comment]
Good work! Congratulations!

**Comment by tu-maurice** [comment]
@bussmann Thanks.
@psychocoderHPC Thank you for helping me.
