### ISSUE TITLE
force-matrix-test: incomplete type GetWorkDiv

### ISSUE THREAD

**Issue by tu-maurice** [ComputationalRadiationPhysics/nbody-alpaka#2]
I've added the usage of shared mem in the branch sharedmem-force-matrix-kernel.

After fixing most of the errors I am stuck with the last one:

```
(...)/tests/forceMatrixKernel/forcematrix_test.cpp:243:17:   required from here
(...)/alpaka/include/alpaka/workdiv/Traits.hpp:73:29: error: incomplete type ‘alpaka::workdiv::traits::GetWorkDiv<alpaka::acc::AccCpuSerial<std::integral_
constant<long unsigned int, 2ul>, long unsigned int>, alpaka::origin::Block, alpaka::origin::Thread, void>’ used in nested name specifier
                 ::getWorkDiv(
```

The part of the code where I'm calling the getValidWorkDiv to create the work division hasn't changed. So I'm guessing it's either some class order issue or there is another way of creating a workdiv if the kernel uses extern shared memory.

**Comment by bussmann** [comment]
I suggest to have a look at the DGEMM example in the Alpaka repo.

**Comment by tu-maurice** [comment]
Thanks. The error was well hidden... Apparently there is alpaka::Thread and alpaka::Threads. The later one was the correct one.
